### ISSUE TITLE
Package installation fails for python3

### ISSUE THREAD

**Issue by al3k** [redacted/XKCD-password-generator#108]
Collecting xkcdpass
  Downloading https://files.pythonhosted.org/packages/2e/06/fad1571c78759c0e77ac9f689282297725800eb66e19e62c3e2413225e99/xkcdpass-1.17.0.tar.gz (2.1MB)
    100% |################################| 2.1MB 4.5MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-kpp9rf3x/xkcdpass/setup.py", line 11, in <module>
        long_description=open('README.rst').read(),
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 6812: ordinal not in range(128)

**Comment by redacted** [comment]
Definitely - it looks like the 1.17.0 was the first release that included non-ASCII characters in the README, which is causing the issue. 

Could you test this for me: Change
`long_description=open('README.rst').read(),`
to 
`long_description=open('README.rst', encoding='utf-8').read(),`
in `setup.py`, then try `python setup.py install`. That should enforce the encoding, and if it works I'll push a new version straight away.

**Comment by al3k** [comment]
I have tested your proposed change and it indeed solves the issue.
Thanks  and sorry for the belated response.

**Comment by redacted** [comment]
Hey, I pushed a new version to pypi yesterday with the above fix included. Can you confirm it works on your machine as well?

**Comment by al3k** [comment]
I have tested and it works fine. Thanks !

**Comment by redacted** [comment]
Great! Thanks for letting me know
