### ISSUE TITLE
Feature request : use multiple wordfiles

### ISSUE THREAD

**Issue by FrankySnow** [redacted/XKCD-password-generator#110]
Hello,
it would be nice to generate passphrases based on multiple wordfiles, providing a much higher entropy.

Even nicer : specify how many words to use from which wordfile.

**Comment by redacted** [comment]
Great idea - I'll look into this as soon as I have some time!

**Comment by EvansJahja** [comment]
I think if only `-w -` allows reading from STDIN, `cat a.txt b.txt | xkcdpass -w -` would work. But it seems that it doesn't support STDIN yet.

**Comment by PrivacyStan** [comment]
I've got a specific use case where I need to generate passphrases based on multiple word files. User selects 1,2, or even 3 custom word files. The passphrase is generated, mixing in general word files where needed. Any progress or plans for this feature?

**Comment by ghyde** [comment]
@PrivacyStan You can always concatenate multiple word files to generate a new word file.

```
cat a.txt b.txt c.txt | sort -u > custom.txt
xkcdpass -w custom.txt
```

**Comment by redacted** [comment]
Release 1.19.0 has initial support for multiple word files, when the argument is a comma-separated list 
`> python xkcd_password.py -w static/legacy,static/fr-freelang,static/fin-kotus`
`conductor enjeu nilellä derby malaise ruskistaa`

If you have any feedback on the current implementation please let me know!
