### ISSUE TITLE
FEAT: an option to have a only politically correct and positive words

### ISSUE THREAD

**Issue by pascalandy** [redacted/XKCD-password-generator#113]
Hi,

I want to use XKCD to generate trial usernames. 

Something like unfixed, sardine scandal are not words I would like to give users. 

Any ideas of how I could accomplish this?

**Comment by redacted** [comment]
The easiest way I can think of would be to create a new word list (any plain text file with one word per line will work), then use the `-w` option to force the generator to use that list. For a starting point, the EFF lists are under 8k entries and shouldn't have many potentially controversial entries - not a fun manual job I know, but not insurmountable!

**Comment by pascalandy** [comment]
That make sense.

I'm surprised that such a request is not more popular. I'll do a PR starting with a small list and let the community grow it.
