### ISSUE TITLE
French words list could be better

### ISSUE THREAD

**Issue by webafrancois** [redacted/XKCD-password-generator#115]
I'm french speaker.
French words list aren't good. Many accents are not respected :
We can read : 
- "a^cre" instead of "âcre"
- "a`-propos" instead of "à-propos"
- "abandonne'" instead of "abandonné"
- "paranoi"a" instead of "paranoïa"
- some words are not words but some abbreviation like "al." (?) "ac."  I think those words could not be included.
- And every word is written 2 times.

I submit a corrected list with accents, without words with ".", and without duplications.
The old list count : 276506 words (which contains all words in double)

The new list contains : 138253 words.

[proper-french-list.tar.gz](https://github.com/redacted/XKCD-password-generator/files/3687958/proper-french-list.tar.gz)

**Comment by redacted** [comment]
Hi! Apologies for the delay in getting to this. 

Which word list are you seeing the issue in? I ran some tests with [fr-freelang](https://github.com/redacted/XKCD-password-generator/blob/master/xkcdpass/static/fr-freelang) and [fr-freelang-bernard-vivier](https://github.com/redacted/XKCD-password-generator/blob/master/xkcdpass/static/fr-freelang-bernard-vivier) and see correct accenting, and only ~23k entries. 

I'm more than happy to add another French list if you can confirm where it originated to ensure the licences are OK

**Comment by webafrancois** [comment]
I took the french list in your README.rst of this repository

> French: Cleaned version of this list. Public domain.  
> https://packetstormsecurity.com/files/download/32007/french.gz
You mention that is a Public Domain, but there is no licence in the .gz file
But this file isn't correctly written.
I correct it and publish on this post.

**Comment by StudioEtrange** [comment]
Please incorporate this proposed dictionnary because
 fr-freelang and fr-freelang-bernard-vivier
have injourious words !
like "salope" => means bitch
or "viol" => means rape

**Comment by redacted** [comment]
Thank you for your contribution - these changes have been made in v1.17.4 or later

**Comment by Cor-J** [comment]
Hello,
The wordlist provided by @webafrancois is in utf8, which isn't correctly read by KeepassXC on windows.
Here is a cp1252 version which  correctly shows accentuated letters.
[cp1252_french.txt](https://github.com/redacted/XKCD-password-generator/files/6733581/cp1252_french.txt)
