### ISSUE TITLE
[FR] allow uppercase, number and special characters in password

### ISSUE THREAD

**Issue by fazlerabbi37** [redacted/XKCD-password-generator#118]
I have been using XKCD-password-generator for a monh now and I think it is awesome! I know the whole point of the XKCD-password-generator is to be a memorable password but there are some websites that will not accept a lower case only password. SO I guess some easy substitution with uppercase, number or special characters would not be a big trouble.

For example, the KeePass plugin [Readable Passphrase Generator](https://bitbucket.org/ligos/readablepassphrasegenerator) has a setting call `'Mutators'` which can be set to `'Standard'` where it mutates the password with number and uppercase.

**Comment by redacted** [comment]
The current `--case / -C` flag allows some mutation, and the `--delimiter` argument might help with special characters or numbers. Adding in "1337" style mutation might be worth looking at though (i.e., replacing a certain percentage of letters with a number, e to 3 etc. Would that address your request?

**Comment by fazlerabbi37** [comment]
Well I installed the apt version of the software which is old and I didn't notice the switches, my bad. The `-C` flag solves the case problem.

---

This is just a thought that it would be great if we could put multiple delimiters to be used one after another like:
```
xkcdpass -d='|,>'
handheld|unruly,sarcastic>AMIGO|pebbly,neuter
```
and the "1337" like mutation would solve the entire problem I described.
