### ISSUE TITLE
[FR] More wordlists

### ISSUE THREAD

**Issue by Mikaela** [redacted/XKCD-password-generator#121]
I have been liking xkcdpass for some time and recently I learned that [The Diceware Passphrase Home Page](https://world.std.com/~reinhold/diceware.html#Diceware%20in%20Other%20Languages|outline) has wordlists for many languages.

I would especially like to see [Esperanto](https://esperantajxo.blogspot.com/2014/07/dajsvaro.html) and [Czech](https://world.std.com/~reinhold/diceware_wordlist_cz.txt)

**Comment by redacted** [comment]
Provided the licenses on the word lists are compatible with distribution, I don't have any problem adding more. There appears to be an issue with that website though so I can't confirm that.

If you do find another source for the word lists you'd like included, please do update this issue!

**Comment by Atronach** [comment]
> Provided the licenses on the word lists are compatible with distribution, I don't have any problem adding more. There appears to be an issue with that website though so I can't confirm that.
> 
> If you do find another source for the word lists you'd like included, please do update this issue!

Hello,

if those links were inaccessible before, they are now. I'm specifically interested in the Czech wordlist. It's distributed w/ GNU/GPL as you can see [here.](https://theworld.com/~reinhold/diceware.html)

Thanks.
