### ISSUE TITLE
Allow specifying multiple word files to unify into word list

### ISSUE THREAD

**Issue by PeterNerlich** [redacted/XKCD-password-generator#136]
Allow specifying `-w`/`--wordfile` multiple times without the last one overriding previous occurances, but causing all files to be read and the resulting word list to be the union of the word lists of the individual dictionaries.

Example:

    $ xkcdpass -w ger-anlx -w eff-short
    verleiht drift recap singen scarf kasten

**Comment by redacted** [comment]
Hi Peter! Multiple word files have been supported since v1.19.0 by providing a comma-separated list:

```
$ xkcdpass -w ger-anlx,eff-long                                                                                                                                                                                                                                                                                                                                                                                                                                                 
schieben supernova stunt brachte zweiten exemplary 
```

I hope that addresses your use-case

**Comment by PeterNerlich** [comment]
Aaah cool! Yes, now that I read the help messages again, I do see it; I apparently just glanced over it before.
