### ISSUE TITLE
xkcdpass version 1.19.3 doesn't work

### ISSUE THREAD

**Issue by ayushnix** [redacted/XKCD-password-generator#146]
I'm getting this error whenever I execute xkcdpass.

```
Traceback (most recent call last):
  File "/usr/sbin/xkcdpass", line 33, in <module>
    sys.exit(load_entry_point('xkcdpass==1.19.3', 'console_scripts', 'xkcdpass')())
  File "/usr/sbin/xkcdpass", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 928, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 518, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for xkcdpass
```

**Comment by anakimluke** [comment]
What's the OS version you are running on? Did you install it via pip or manually? Did you provide xkcd any arguments when you ran this?

**Comment by ayushnix** [comment]
I'm using Arch Linux. It is using python version 3.10.2. I've installed xkcdpass version 1.19.3 from the [AUR](https://aur.archlinux.org/packages/xkcdpass). I didn't try installing it using pip. I ran xkcdpass with and without arguments and received the same error.

**Comment by anakimluke** [comment]
Seems it's not an issue with xkcdpass specifically. Other people were having similar issues with other packages.

Apparently, a fix is to [rebuild your AUR packages](https://www.reddit.com/r/archlinux/comments/rf6c84/psa_python_310_is_in_core_rebuild_your_aur/) but I don't have any experience with that, so I can't help you there ;)

**Comment by redacted** [comment]
Hey @ayushnix - I'm afraid I don't have anything to do with the AUR package (and I'm not very familiar with arch in general). Does the pip installed version work for you?

**Comment by ayushnix** [comment]
@anakimluke thanks, a reinstallation worked.

@redacted my bad, sorry for the noise.
