### ISSUE TITLE
Extra delimiters when using "-R" option

### ISSUE THREAD

**Issue by davidshen84** [redacted/XKCD-password-generator#150]
## With `-d`, delimiters are inserted between the words

```shell
> xkcdpass -d.
garnet.dallying.eclipse.childcare.comply.slider
```

re. https://github.com/redacted/XKCD-password-generator/blob/master/xkcdpass/xkcd_password.py#L343C24-L343C24

## With `-R`, delimiters are inserted at the beginning, the end and between the words
```shell
> xkcdpass -R
7sturdy#sporting^collector@boned&halogen*undying7
```

re. https://github.com/redacted/XKCD-password-generator/blob/master/xkcdpass/xkcd_password.py#L366

I wonder if it is implement like so intentionally. I think `-R` should only insert delimiters between the words.

**Comment by anakimluke** [comment]
You're right. That's a bit unsettling, isn't it? I think the -R implementation should be changed as you said. Do you want to make a PR? Or do I do it? :)

**Comment by davidshen84** [comment]
I think one line would do.

```
return ''.join(map(lambda w: choose_delimiter(delimiters) + w, words))[:-1]
```

I have not tested it. I will create a PR tonight if you have not fixed it already.

**Comment by davidshen84** [comment]
Do you plan to merge it, or is it not worth the change?

**Comment by anakimluke** [comment]
I don't have commit rights on this repo ;)

I'll continue the conversation at #151

**Comment by redacted** [comment]
Closing this as the PR is merged, thank you both!
