### ISSUE TITLE
examples are being installed to site-packages after setup.py fixes

### ISSUE THREAD

**Issue by benkohler** [redacted/XKCD-password-generator#153]
I'm adding 1.19.4 to gentoo repos and our python checks have started throwing an error:

* python3_11: running distutils-r1_run_phase distutils-r1_python_install
 * The following unexpected files/directories were found top-level
 * in the site-packages directory:
 *
 *   /usr/lib/python3.11/site-packages/examples
 *
 * This is most likely a bug in the build system.  More information
 * can be found in the Python Guide:
 * https://projects.gentoo.org/python/guide/qawarn.html#stray-top-level-files-in-site-packages

The very last commit in 1.19.4 modifies setup.py to use an exclude rather than an include, I think we need to add examples to the list after all the test matches.

**Comment by redacted** [comment]
Thank you for flagging this, and for the PR to correct - it is merged in v1.19.7
