### ISSUE TITLE
Impossible acrostics makes the script hang forever

### ISSUE THREAD

**Issue by thiderman** [redacted/XKCD-password-generator#20]
If you ask the app to create acrostics that it cannot fulfill (`-a PASS`, capitals important, is an example) it will hang forever.

It's pretty easy to add a workaround - either there is a limit on tries, or there is a timeout after `x` seconds. Tell me which is preferable and I'll PR it! :palm_tree:

**Comment by redacted** [comment]
I actually can't reproduce the hang on the current code

    $ python xkcd_password.py -a PASS
    > Pharaoh Antarctic Scotch Soviet
    $ python xkcd_password.py -a _
    > No words found starting with _

The `find_acrostic` function was rewritten to use a dictionary keyed by first letter, and should error if you ask for a letter with no words.

**Comment by thiderman** [comment]
Wow, I didn't even update to the latest code before checking. Please excuse my face, and I apologize for stealing a little bit of your day with this drivel! :+1:

**Comment by redacted** [comment]
No worries at all!
