### ISSUE TITLE
Works as root, not as user.

### ISSUE THREAD

**Issue by pashdown** [redacted/XKCD-password-generator#24]
On Linuxmint 17.1, after a "pip install xkcdpass" as root, it works fine as the root user, but this is the error it coughs out when running as a unprivileged user:

`Traceback (most recent call last):
  File "/usr/local/bin/xkcdpass", line 9, in <module>
    load_entry_point('xkcdpass==1.2.5', 'console_scripts', 'xkcdpass')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2362, in load_entry_point
    raise ImportError("Entry point %r not found" % ((group,name),))
ImportError: Entry point ('console_scripts', 'xkcdpass') not found`

**Comment by redacted** [comment]
I can't reproduce this on either Ubuntu 15.04 or OS X 10.10. When I have a chance over the weekend I will spin up a Mint VM and test there, but my gut feeling is that this is an issue with pip or python install itself.

**Comment by redacted** [comment]
I created a fresh Mint VM (Linux Mint 17.1 Cinnamom), installed pip (`sudo apt-get install python-pip`) then xkcdpass (`sudo pip install xkcdpass`).

Running `xkcdpass`worked as expected; I can't reproduce your issue.

A brief search of the specific `ImportError` message you're seeing suggests permissions errors (e.g., https://github.com/wal-e/wal-e/issues/20) - maybe try looking in that direction?
