### ISSUE TITLE
This code is basically one line

### ISSUE THREAD

**Issue by Taiiwo** [redacted/XKCD-password-generator#26]
I get that this contains some fancy options for user prompting and such, but if users are coming here for a simple solution to auto-generating memorable and secure passwords, they could just use this:

```python
from random import SystemRandom as r
' '.join(r().sample(open('wordlist.txt', 'r').read().splitlines(), 4))
```

Where 4 is the length, in words, of the password.

**Comment by redacted** [comment]
Running `xkcdpass` from the command line will generate a secure passphrase (following recommendations of diceware author for length). Having options to control the format of this passphrase is a strict improvement. Closing issue.
