### ISSUE TITLE
Move code examples out of Python package

### ISSUE THREAD

**Issue by bignose-debian** [redacted/XKCD-password-generator#33]
Code examples are not intended for import as part of the ‘xkcdpass’ Python package, so should not be modules in that directory.

Instead the code examples more resemble documentation, and should not be installed in any importable Python package.

**Comment by bignose-debian** [comment]
My suggested change for this is in the branch at https://notabug.org/bignose/XKCD-password-generator/src/feature/separate-code-examples

Please merge those changes if you agree.

**Comment by redacted** [comment]
Thanks for the fix! Merged in latest release (1.4.4).
