### ISSUE TITLE
Options set by command-line, environment variables, and config files

### ISSUE THREAD

**Issue by bignose-debian** [redacted/XKCD-password-generator#34]
Configuring the behaviour of the ‘xkcdpass’ command via user-chosen options is good. It would be good to specify those also via corresponding environment variables and via corresponding options in configuration files.

**Comment by bignose-debian** [comment]
Would you be open to adding a dependency on, e.g., [ConfigArgParse](https://pypi.python.org/pypi/ConfigArgParse) that makes this easy to do?

**Comment by redacted** [comment]
In-built modules can get almost all the way to ConfigArgParse: using ConfigParser/configparser to set defaults as shown in [this example](http://stackoverflow.com/questions/3609852/which-is-the-best-way-to-allow-configuration-options-be-overridden-at-the-comman/5826167#5826167).

I would be happier to keep external dependencies to an absolute minimum.
