### ISSUE TITLE
Move tag “xkcdpass-1.4.4” to correct commit

### ISSUE THREAD

**Issue by bignose-debian** [redacted/XKCD-password-generator#35]
The tag “xkcdpass-1.4.4” currently points to a commit where the version is still “1.4.3”.

Commit 3ad73d6cefc1d511882b7731ed44f2469c589195 (current head as of this report) sets the version to “1.4.4”, I think the “xkcdpass-1.4.4” tag needs to be moved there. Perhaps the message on that commit should state that it increments the version.

**Comment by redacted** [comment]
Thought I had already fixed this - thank you for the catch! Tags should be correct now
