### ISSUE TITLE
Migrate command-line parsing to ‘argparse’

### ISSUE THREAD

**Issue by bignose-debian** [redacted/XKCD-password-generator#36]
The ‘optparse’ module is replaced by ‘argparse’ in Python 2.7 and later; that is, every supported Python version. In Python 3, ‘optparse’ is deprecated in favour of ‘argparse’.

Migrate the command-line parsing from the ‘optparse’ module to the superior ‘argparse’.

**Comment by bignose-debian** [comment]
My suggested implementation of this is the ‘feature/migrate-to-argparse’ https://notabug.org/bignose/XKCD-password-generator/src/feature/migrate-to-argparse branch.

**Comment by redacted** [comment]
I don't see any problem with this at all. Originally `optparse` was chosen to allow the code to work on Python versions below 2.7, which is probably not a major concern today. 

The linked branch looks completely fine, would you be comfortable with it being merged as-is?

**Comment by bignose-debian** [comment]
Glad you like it! Yes, if you approve of that branch, please merge it.

**Comment by bignose-debian** [comment]
> Originally optparse was chosen to allow the code to work on Python versions below 2.7, which is probably not a major concern today.

I have updated the above branch, to correct the minimum Python requirements.

**Comment by redacted** [comment]
Merged in 1.5.0 release
