### ISSUE TITLE
Underscore character not helpful in command-line options

### ISSUE THREAD

**Issue by bignose-debian** [redacted/XKCD-password-generator#37]
The name ‘valid_chars’ is a fine name in Python code. The command-line option for this should not have an underscore, though; switching between hyphens and underscores is cognitively difficult.

The command-line option name should IMO be ‘--valid-chars’ (only hyphens).

**Comment by bittner** [comment]
I believe an option using a hyphen (`-`) is automatically converted to a member containing an underscore (`_`) instead by `argparse` and `optparse`, anyway.  Hence, code-wise there should be little to no change.

**Comment by redacted** [comment]
Seems like a good change. It could be rolled up with the general move to `argparse` (issue #36)

**Comment by bignose-debian** [comment]
> It could be rolled up with the general move to argparse (issue #36)

I'd say the history will be easier to understand in retrospect if those changes are kept separate.

**Comment by redacted** [comment]
Agreed. I will merge in the argparse changes, and then make this change.

**Comment by redacted** [comment]
Fixed in 1.6.0 release
