### ISSUE TITLE
Set of contributors should be in one canonical file

### ISSUE THREAD

**Issue by bignose-debian** [redacted/XKCD-password-generator#38]
The set of contributors is currently inserted into multiple files. This makes those files more awkward to maintain, and the duplication risks them diverging.

It would be easier to maintain in a single file devoted to the purpose, such as a top-level ‘CONTRIBUTORS’ document.

**Comment by bignose-debian** [comment]
See my branch https://notabug.org/bignose/XKCD-password-generator/src/issue/distinguish-copyright-info for a suggested change to use this canonical document.

**Comment by redacted** [comment]
Merged in release 1.6.2
