### ISSUE TITLE
Add configuration for command completion in Bash

### ISSUE THREAD

**Issue by bignose-debian** [redacted/XKCD-password-generator#39]
The Bash feature “Programmable Completion” allows configuring the shell to perform custom completion (i.e. by pressing the TAB key for arguments).

Add an example configuration for command completion of the ‘xkcdpass’ command.

**Comment by bignose-debian** [comment]
See my branch https://notabug.org/bignose/XKCD-password-generator/src/feature/bash-completion for a suggested change to add this feature.

**Comment by bignose-debian** [comment]
The above branch is now re-based from this repository's current ‘master’.

**Comment by redacted** [comment]
merged to master now
