### ISSUE TITLE
Avoid weak RNG unless user explicitly permits it

### ISSUE THREAD

**Issue by sptankard** [redacted/XKCD-password-generator#42]
I think it would be a good idea to avoid falling back to weak RNG (`random.Random`) unless the user has explicitly expressed that they are OK with it. This is on the idea that it is often better for the command to fail than to (unknowingly) get a weakly random result. 

In case of normal evocation, lack of secure random (`random.SystemRandom`) would cause the command to fail. The error message can instruct the user to try again with e.g. `--allow-weak-rng` option if they are OK with weak random.

I am willing to implement this if you think it is a good idea.

**Comment by redacted** [comment]
That's a very good idea. If you are willing to build it it'd be a great addition

**Comment by sptankard** [comment]
Let me know what you think about that patch. Usage of `global` keyword is not ideal but I think doing it more elegantly would require some restructuring (e.g. an `XKCDPass` class).

**Comment by redacted** [comment]
Merged #44, closing issue
