### ISSUE TITLE
Print statistics

### ISSUE THREAD

**Issue by Freso** [redacted/XKCD-password-generator#46]
It would be great if there was an option to output statistics based on given parameters (wordfile, whether an acrostic was used, number of words in the phrase): what is the sample size of words, what is entropy (possibly full knowledge vs. no knowledge).

**Comment by Freso** [comment]
I'm blind. `-V`/`--verbose` gives me exactly what I want. Thanks! :)

**Comment by amiryal** [comment]
Actually, when specifying an acrostic, the stats ignore it. I opened #58 to report that.
