### ISSUE TITLE
Not all words used (?)

### ISSUE THREAD

**Issue by davidak** [redacted/XKCD-password-generator#47]
I have 624565 words in my wordlist, but xkcdpass displays that it has only 176933.

![bildschirmfoto 2016-08-07 um 05 18 13](https://cloud.githubusercontent.com/assets/91113/17460288/44e73bd6-5c5f-11e6-97fb-2f9335e4abc0.png)

**Comment by redacted** [comment]
There's a few settings (and design choices) that could affect how many words the generator loads from a wordlist. 

The list gets deduplicated, so if you created your list by joining other lists this could be a factor.

The default command line options load in words between 5 and 9 characters long. Both bounds are fairly arbitrary, and were picked to enforce minimum total password length and to stop users getting esoteric technical or scientific words in passwords (this is a severe issue when using the Linux standard dict wordlists). You could run `xkcdpass -V --min 1 --max 100` or similar to see how significant this effect is.

If you test those and are still missing words let me know. The only other thing I can think of is that the regex filtering for `--valid-chars` is causing problems but that doesn't seem likely.

**Comment by davidak** [comment]
I don't used `--valid-chars`. With `--min 1 --max 100` all words are used, thanks!

Is the delimeter included in the entropy?

**Comment by redacted** [comment]
No worries, glad it's working for you! 

The delimiter is not currently included in the entropy calculation (see https://github.com/redacted/XKCD-password-generator/blob/master/xkcdpass/xkcd_password.py#L144). Just using the number of words and wordlist length makes for easier comparison with entropy of more traditional passwords.
