### ISSUE TITLE
random delimiter support

### ISSUE THREAD

**Issue by anarcat** [redacted/XKCD-password-generator#56]
while it's nice that you can change the delimiter from space to whatever string, it would be even better if xkcdpass would have the (optional) feature to inject random symbols and digits as separators.

by default, the search space of xkcdpass-generated passwords is quite large, but that's mostly due to the length of the password. while one can't assume that the password to be cracked will be all lowercase letters in the general case, that means the password generation routine becomes yet another "something you know" and allows the attacker to reduce the search space significantly once they know you use xkcdpass.

allowing for random passwords would force attackers to not limit themselves to 26 characters. adding numbers and symbols to that space would add about 40 bits of entropy to every password, at little cost to the human memory.

```
[1020]anarcat@curie:~$ xkcdpass  | wc
      1       6      46
[1021]anarcat@curie:~$ xkcdpass  | wc
      1       6      46
[1021]anarcat@curie:~$ xkcdpass  | wc
      1       6      52
[1021]anarcat@curie:~$ xkcdpass  | wc
      1       6      45
[1021]anarcat@curie:~$ xkcdpass  | wc
      1       6      54
[1021]anarcat@curie:~$ xkcdpass  | wc
      1       6      55
[1021]anarcat@curie:~$ qalc
> log2(26^55)

  log2(26^55) = approx. 258.52418

> log2((26+20)^55)

  log2((26 + 20)^55) = approx. 303.79591

> log2((26)^46)

  log2(26^46) = approx. 216.22023

> log2((26+20)^46)

  log2((26 + 20)^46) = approx. 254.08385

> 
```

thanks for your consideration!

**Comment by redacted** [comment]
Thanks for the suggestion! 

I assume you mean that each delimiter is random and different, like `correct ? horse ] battery 7 staple`?

**Comment by anarcat** [comment]
basically, yes. i was thinking of *replacing* spaces, so it would be `correct+horse]battery7staple`, but yes, that's the generally idea.

**Comment by Garrett-R** [comment]
I'm not sure I agree with this proposal.  The point of that XKCD comic was saying we should use easy to remember passwords, but random symbols are hard to remember.  At least for me, the cost of memorizing them is more than the added entropy.

I think adding random delimiters will (very minory) bloat this library's API.  Why not just use python and replace the delimiter one at a time with a random symbol if you have that use-case.

**Comment by redacted** [comment]
I've added a script to the example folder which addresses this issue:

https://github.com/redacted/XKCD-password-generator/blob/master/examples/example_postprocess.py

```
% xkcdpass -c 3 -n 4 -a xkcd | ./example_postprocess.py
xenon * kaput ' capriole . doublet
x-axis ) kowtow > copier ) dockland
xebec ) knobby 0 columbine 1 defogger
```

I think this is probably the best (and most flexible) solution, rather than adding bloat as @Garrett-R pointed out.
