### ISSUE TITLE
ship with the EFF word list (by default?)

### ISSUE THREAD

**Issue by anarcat** [redacted/XKCD-password-generator#57]
the current word list is okay - it's a curated list specially crafted with a few interesting properties.

but it wasn't designed specifically for password generation. the EFF actually crafted a [word list](https://www.eff.org/deeplinks/2016/07/new-wordlists-random-passphrases) specifically for that purpose that you may want to consider shipping as an alternative or as a default word list.

**Comment by redacted** [comment]
Thanks for the suggestion! I've added a comment to the README linking that list to people. I don't see licence information on that EFF page so I'm not sure about including it in the packaged version. I may contact the EFF though.

**Comment by jcb82** [comment]
Hi-Joseph Bonneau from EFF here. All material on the EFF website, including the password lists, is licensed as CC-BY (https://www.eff.org/copyright) so it can be included freely (with attribution)

**Comment by redacted** [comment]
Hey Joseph - thanks for the info. I'll take a closer look this weekend!
