### ISSUE TITLE
When using ACROSTIC, report accurate metrics still

### ISSUE THREAD

**Issue by amiryal** [redacted/XKCD-password-generator#58]
The `-V` report should reflect the exact entropy (assuming perfect RNG) of the generated password, taking all parameters into account.

Currently, when combining the `-a` and `-V` options, the printed metrics do not take the acrostic into account, i.e. they use the default `numwords` and disregard limiting the first letter of each word.

**Comment by amiryal** [comment]
Looking at the code, I see some moderate refactoring is due, in order to fix this issue. Before I begin to work on a PR, I would like to share my plans here.

I am thinking to always use the `acrostic` and its `worddict` in `generate_xkcdpassword()` (instead of `numwords` and `wordlist`), and if no acrostic was given, use `acrostic = "_" * numwords` and `worddict = { '_': wordlist }`. All this should happen before the call to `verbose_reports()`, so the calculations there can take the acrostic into account.

What do you think?

**Comment by amiryal** [comment]
Work in progress can be seen [here](https://github.com/redacted/XKCD-password-generator/compare/master...amiryal:master). I would like to make the interface with `_to_acrostic_and_worddict` less fragile, sprinkle some more comments around the code and improve the commit messages before submitting the PR.

Let me know if you would like me to submit as-is, because it might be a while before I have time to work on it again.

**Comment by redacted** [comment]
Thanks for your work on this - I like your solution to the problem and I can see a few places the wider code base could be refactored to streamline this approach.

Feel free to open and update the PR as suits you. I'll make some time later this week to merge it in some form!

**Comment by redacted** [comment]
Fixed in latest release, xkcdpass-1.11.0
