### ISSUE TITLE
Failed to create process when running xkcdpass

### ISSUE THREAD

**Issue by defaulthtm** [redacted/XKCD-password-generator#60]
installed using pip and ran got a failed to create process error when running 
Python on the server I ran from is installed in a path that has spaces in it.
Updating xkcdpass-script.py to quote the python path after the #! resolved the issue
as an example #!"c:\program files (x86)\python 3.5\python.exe"

**Comment by redacted** [comment]
I haven't been able to reproduce this on my Windows boxes with the official python installer. If there is a space in python's install path the path after #! is correctly quoted. However, I was able to cause the error by adding a space to the path after installing python - it seems to confuse pip and the path is no longer quoted. 

Would it be possible for you to reinstall python using the [latest installer](https://www.python.org/downloads/) and try installing xkcdpass again? 

I checked the [python 3 docs](https://docs.python.org/3/using/windows.html?highlight=windows#shebang-lines) and the shebang (`#!`) in xkcdpass is correct for Windows. I

**Comment by defaulthtm** [comment]
For reference Windows Server 2012 is the OS involved. This might be a pip defect...

The Python 3.6 installer correctly quoted the path 
uninstalled and reinstalled on a 3.5.0 machine and the initial path is 
#!c:\program files (x86)\python 3.5\python.exe
quoting fixed it - I'll see if I can upgrade Python there
I agree that the shebang is correct FWIW - it is the missing quotes around the path
