### ISSUE TITLE
Decide if you want to maintain the snap created

### ISSUE THREAD

**Issue by roxyd** [redacted/XKCD-password-generator#66]
Hello,

I created a snap using [snapcraft.io](url) which allows people to download the code and run it in a contained environment.
You can view my snap here: https://github.com/roxyd/snapcraft-snaps/tree/master/xkcdpass
You can download it from the ubuntu store with "sudo snap install xkcdpass" after you follow instructions to download snapd: https://snapcraft.io/docs/core/install
More information can be found on snaps here: https://snapcraft.io/docs/snaps/intro

I have no problem maintaining the snap, but if you would like to maintain it yourself, please let me know and I can transfer ownership.

If you do not wish to maintain it at this time but change your mind later, you can post here if you are not able to contact me: https://forum.snapcraft.io/t/call-for-testing-xkcdpass-my-first-snap/194/17

**Comment by redacted** [comment]
Hey roxyd,

Thanks for your interest in the project and your work! And my apologies for the delay in getting back to you. I have no issue with you continuing to manage the snap if you are happy to - the debian packages are similarly maintained by another developer (both systems I have no experience with). 

That said, if there is anything I can help with please let me know. For example, the tagging of releases in the repo was started to help the debian maintainer.

**Comment by roxyd** [comment]
it's no problem at all. I don't mind maintaining the snap. I'll ping you if I have any questions.

**Comment by redacted** [comment]
Perfect, thank you!
