### ISSUE TITLE
Entropy-based password length

### ISSUE THREAD

**Issue by tomaskrizek** [redacted/XKCD-password-generator#67]
Since it's possible to use different wordfiles, using number of words to specify the passphrase length can produce variably strong passphrases, depending on the wordfile.

User should have an option to specify required entropy / password strength which would take into account the length of the wordfile and produce a passphrase of similar strength regardless of the wordfile that is used.

Example:
```console
$ xkcdpass -w legacy -e 75
nucleus Mboya Moldova Scopes parody
$ xkcdpass -w eff-long -e 75
affair ounce hatchback guidance cubical onlooker
$ xkcdpass -w eff-short -e 75
delay dizzy agile ebony twirl tweak aloft quake
```

This approach should be used as default when no specific word limit is provided. Entropy could be specified in passphrase strength levels instead of bits. A warning could also be displayed on error output for low entropy passphrases.

This feature would most likely have to be mutually exclusive with acrostic.

**Comment by amiryal** [comment]
> This feature would most likely have to be mutually exclusive with acrostic.

See PR #61, which should address your concerns. With that fix implemented, I suppose you could repeat the acrostic as many times as necessary to reach the desired entropy (or use less letters, if the requested entropy is low).
