### ISSUE TITLE
Max/min options cannot be called alone

### ISSUE THREAD

**Issue by justinbass** [redacted/XKCD-password-generator#69]
Issue: I would expect that just specifying --max would work. Apparently --min is required as well. The code should set min=max or max=min to allow this to work.

$ xkcdpass --max=4
The maximum length of a word can not be less than the minimum length.
Check the specified settings.

$ xkcdpass --min 10
The maximum length of a word can not be less than the minimum length.
Check the specified settings

$ xkcdpass --max=4 --min=4
[correct output]

**Comment by redacted** [comment]
This is fixed in the version 1.12.0 - thank you for the report
