### ISSUE TITLE
Feature request: Random non-whitespace delimiter or specify a minimum number of capital letters?

### ISSUE THREAD

**Issue by hcal** [redacted/XKCD-password-generator#70]
Would it be difficult to add an option for a random non-whitespace delimiter or  a minimum number of capital letters?

**Comment by redacted** [comment]
It's a suggestion that has come up before but building it into the library isn't something I'd like to do - there's an example script of how you can achieve a similar goal using imports https://github.com/redacted/XKCD-password-generator/blob/master/examples/example_postprocess.py
