### ISSUE TITLE
incosistency between documentation and usage of wordlists

### ISSUE THREAD

**Issue by tomaskrizek** [redacted/XKCD-password-generator#73]
`xkcdpass --help` suggests `eff-long` wordlist is used by default, but if either `/usr/share/cracklib/cracklib-small` or `/usr/share/dict/cracklib-small` exist, they will be used instead.

I kept [this list](https://github.com/redacted/XKCD-password-generator/blob/master/xkcdpass/xkcd_password.py#L95) in 6e8d63b451165b89d922619ad9f8b5fc1a9d6022, because that's the way the wordlists were selected before.

I'd be in favor of always using `eff-long` by default and removing all the other options. Is there any reason to keep the other options?

**Comment by redacted** [comment]
In the latest release this is fixed - thank you for the catch. I've left the functionality in for the moment as it may be useful to handle edge cases where the default wordlist is missing or inaccessible (admittedly unlikely, but it's not particularly expensive to check if it exists).
