### ISSUE TITLE
Tests assume a specific interpreter name

### ISSUE THREAD

**Issue by bignose-debian** [redacted/XKCD-password-generator#77]
The test cases attempt to invoke the Python interpreter in a sub-process. The assumption is that the command `python` will invoke the Python interpreter. This assumption is not universally true, and causes the test cases to fail when the correct Python interpreter does not have that name.

Instead, the current Python interpreter program file path should be interrogated from the `sys.executable` attribute.

**Comment by bignose-debian** [comment]
I have implemented changes to address this bug, in [the ‘wip/issue/use-current-interpreter-name’ branch of my personal fork repository](https://anonscm.debian.org/git/users/bignose/xkcdpass.git/log/?h=wip/issue/use-current-interpreter-name). The branch currently merges cleanly to ‘master’.

**Comment by redacted** [comment]
Hey, thanks for the fix - in the latest release and newest tag

**Comment by bignose-debian** [comment]
Thanks, I'm glad to contribute.
