### ISSUE TITLE
Copyright license grant missing for ‘xkcdpass/static/ita-wiki’

### ISSUE THREAD

**Issue by bignose-debian** [redacted/XKCD-password-generator#78]
The file ‘xkcdpass/static/ita-wiki’ was added in commit 151972d46f149b5e without describing its provenance – what is the source, what is the procedure for rebuilding the file from that source – and without a grant of license in the work.

Please describe how to get the source for that file, how to build that file from its source, and what license is granted to the recipient for exercising actions otherwise restricted by copyright.

**Comment by redacted** [comment]
The file is generated by an MIT-licensed script (project here: https://github.com/mooow/wikistat), and built from dumps of the Italian wikipedia, which is released under Creative Commons Attribution-Share-Alike 3.0. The author of the script suggested the wordlist's inclusion. 

What of the above would be required for inclusion in this project, from your side?
