### ISSUE TITLE
Use of undefined variable 'numwords' in some functions in xkcdpass/xkcd_password.py

### ISSUE THREAD

**Issue by goswami-rahul** [redacted/XKCD-password-generator#92]
in functions **n_words_validator** and **accepted_validator** variable _numwords_ is used or returned without any value assigned to it.
It is not a global variable either.
I think it should be _options.numwords_ or it should be declared global, but not sure.

**Comment by redacted** [comment]
The value of `numwords` is inherited from the parent function `generate_xkcdpassword()` in the case you mention, and is defined within that scope
