### ISSUE TITLE
Reference to German wordlist missing in help

### ISSUE THREAD

**Issue by dploeger** [redacted/XKCD-password-generator#94]
If you look at the command line help, a reference to the included german word list is missing:

```
  -w WORDFILE, --wordfile WORDFILE
                        Specify that the file WORDFILE contains the list of
                        valid words from which to generate passphrases.
                        Provided wordfiles: eff-long (default), eff-short,
                        eff-special, legacy, spa-mich (Spanish), fin-kotus
                        (Finnish)
```

**Comment by anlx-sw** [comment]
there are also issues with the documentation. the base list  provided is https://github.com/dassencio/langcmp/blob/master/wordlists/top10000de.txt. in the readme and documentation the top1000de.txt is linkes (missing one 0).

the correct list ist shipped though - with 9717 lines based on the top10000de.txt

**Comment by redacted** [comment]
Hey, thanks for letting me know - this is corrected in the newest release
