### ISSUE TITLE
Feature Request: Portable executable

### ISSUE THREAD

**Issue by anlx-sw** [redacted/XKCD-password-generator#95]
From a user side of view i would prefer to use a portable executable of xkcdpass on windows.

Python is normally not installed on windows computers or servers and may not be allowed in secure environments becaues it increases the systems attack surface.

A portable executable would also allow to install this tool via https://chocolatey.org/.

Would it be possible to provide a compiled exe as a regular release option?  I think this could be helpful for all kinds of windows users.

**Comment by pascalandy** [comment]
I could PR my docker setup if someone is interested :)

**Comment by Mikaela** [comment]
This might be a bit threadjacking, but have [AppImages](https://appimage.org/) been thought about?

They would be portable executables on Linux and I would be interested in using one (especially if it supported [AppImageUpdate](https://github.com/AppImage/AppImageUpdate/blob/rewrite/README.md) and was gpg/equivalent signed) so I could get new features like #110 sooner without having to remember to keep xkcdpass up-to-date with pip outside of my system repositories.

Currently I seem to be using 1.16.5+dfsg.1-1 while the latest tag in GitHub is  xkcdpass-1.17.3.
