### ISSUE TITLE
Correct spelling of ‘--separator’ option in README document

### ISSUE THREAD

**Issue by bignose-debian** [redacted/XKCD-password-generator#97]
The README document reports a mis-spelling of the `--separator` option, in the Changelog section:

```rst
- **1.15.0** Added `--seperator` argument, German wordlist (GPL 3.0, thanks to @anlx-sw)
```

This should be corrected to match the English word “separator” and the `--separator` option.

**Comment by redacted** [comment]
Good catch, fixed in latest releases!
