### ISSUE TITLE
Tests fail when Python interpreter is not ‘python’

### ISSUE THREAD

**Issue by bignose-debian** [redacted/XKCD-password-generator#98]
When the operating system command ‘python’ does not invoke the expected Python interpreter, the unit tests fail. This is because the tests assume that a subprocess, invoking the ‘python’ command, will correctly run the code for testing.

When this assumption is not true (for example, when the Python interpreter is installed to a non-standard location) the unit tests fail incorrectly.

**Comment by redacted** [comment]
Merging #99 should have fixed this - thanks again
